env = Environment()

VLFEAT_DIR = '../../vl'

env.Append(CPPPATH = [
	VLFEAT_DIR + '/../', 
	'/System/Library/Frameworks/Python.framework/Headers',  # for #include <python.h>
	'/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/numpy/core/include'  # for #include <numpy/arrayobject.h>
	])

# compile flags
flags = '-O3 -DNDEBUG -Wall'
env.Append(CCFLAGS = flags.split())
env.Append(LIBPATH = ['/usr/local/lib/'])

SOURCES_C = [
	VLFEAT_DIR + '/aib.c', 
	VLFEAT_DIR + '/generic.c',
	VLFEAT_DIR + '/hikmeans.c',
	VLFEAT_DIR + '/ikmeans.c',
	VLFEAT_DIR + '/imopv.c',
	VLFEAT_DIR + '/mathop.c',
	VLFEAT_DIR + '/pgm.c',
	VLFEAT_DIR + '/rodrigues.c',
	VLFEAT_DIR + '/stringop.c',
	VLFEAT_DIR + '/getopt_long.c',
	VLFEAT_DIR + '/host.c',
	VLFEAT_DIR + '/imop.c',
	VLFEAT_DIR + '/imopv_sse2.c',
	VLFEAT_DIR + '/mser.c',
	VLFEAT_DIR + '/random.c',
	VLFEAT_DIR + '/sift.c',
	VLFEAT_DIR + '/dsift.c',	
	]

SOURCES_CPP = [
	'mser/vl_erfill.cpp',
	'mser/vl_mser.cpp',
	'sift/vl_sift.cpp',
	'sift/vl_dsift.cpp',
	'sift/vl_siftdescriptor.cpp',
	'imop/vl_imsmooth.cpp',
	'misc/vl_binsum.cpp',
	'kmeans/vl_hikmeans.cpp',
	'kmeans/vl_ikmeans.cpp',
	'kmeans/vl_hikmeanspush.cpp',
	'kmeans/vl_ikmeanspush.cpp',
	'py_vlfeat.cpp'
	]

# libs to link
env.Append(LIBS = ['boost_python', 'python'])

# shared lib
env.SharedLibrary('_vlfeat', source=SOURCES_C + SOURCES_CPP)
